apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          # A tag abaixo é atualizada automaticamente pelo job gitops-update
          # do pipeline de CI (.github/workflows/reusable-python-ci.yml).
          image: 711747463826.dkr.ecr.us-east-1.amazonaws.com/analytics-service:v1.0.0-init
          ports:
            - containerPort: 8005
          envFrom:
            - secretRef:
                name: analytics-service-secrets
          env:
            - name: PORT
              value: "8005"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
