apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    # Troque pela URL real do repositório depois do primeiro push.
    repoURL: https://github.com/jcbarros24/devops-fiap-fase3-challenge.git
    targetRevision: main
    path: gitops/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
