name: evaluation-service

on:
  pull_request:
    paths:
      - "services/evaluation-service/**"
  push:
    branches: [main]
    paths:
      - "services/evaluation-service/**"

jobs:
  ci:
    uses: ./.github/workflows/reusable-go-ci.yml
    with:
      service_name: evaluation-service
      service_path: services/evaluation-service
    secrets: inherit
