name: flag-service

on:
  pull_request:
    paths:
      - "services/flag-service/**"
  push:
    branches: [main]
    paths:
      - "services/flag-service/**"

jobs:
  ci:
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      service_name: flag-service
      service_path: services/flag-service
    secrets: inherit
